/*
Copyright 2018 Google LLC
Copyright 2022 David Gageot

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package handlers

import (
	_ "embed"
	"net/http"
	"strings"
	"time"
)

// engineCSS is the chassis stylesheet: the design tokens, the stage, the
// slide-* classes, the dark palette and the display profiles.
//
// It is generated by `hack/css.sh engine` and committed, rather than built at
// run time or scanned from the presentation folder. A talk's own build cannot
// see these classes: handlers/resources and deck/layouts are embedded in the
// binary, so a released demoit carries no such directories on disk.
//
//go:embed resources/demoit.css
var engineCSS string

// EngineCSS serves the embedded chassis stylesheet.
func EngineCSS(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/css; charset=utf-8")

	// A zero modtime keeps ServeContent from claiming a freshness it cannot
	// know: the stylesheet is compiled into the binary, and the ?hash= query
	// the templates append is what actually busts a cache.
	http.ServeContent(w, r, "demoit.css", time.Time{}, strings.NewReader(engineCSS))
}
